# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 501)
        MainWindow.setStyleSheet("QWidget {\n"
"      background-color: #2e3440;\n"
"    }\n"
"    QLabel#title {\n"
"      font: 75 24pt \"Segoe UI\";\n"
"      color: #88c0d0;\n"
"      background-color: transparent;\n"
"    }\n"
"    QLabel {\n"
"      font: 12pt \"Segoe UI\";\n"
"      color:white;\n"
"      background-color: transparent;\n"
"    }\n"
"QPushButton {\n"
"      background-color: #5e81ac;\n"
"      color: white;\n"
"      border-radius: 10px;\n"
"      padding: 9px 10px;\n"
"      border: 1px solid #4c566a;\n"
"      font: 9pt \"Segoe UI\";\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"      background-color: #81a1c1;\n"
"      border: 2px solid #88c0d0;\n"
"    }\n"
"QPushButton:pressed {\n"
"      background-color: #4c566a;\n"
"      border: 2px solid #3b4252;\n"
"    }\n"
"QProgressBar{\n"
"     background-color: #5e81ac;\n"
"      color: white;\n"
"      border-radius: 13px;\n"
"      padding: 10px 10px;\n"
"      border: 1px solid #4c566a;\n"
"      font: 8pt \"Segoe UI\";\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}\n"
"  \n"
"   QMenuBar{\n"
"     color: white;\n"
"    }\n"
"QLineEdit{\n"
"  background-color: transparent;\n"
"      color: white;\n"
"      border-radius: 10px;\n"
"      padding: 5px 9px;\n"
"      border: 1px solid #4c5660;\n"
"      font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QStatusBar::item {\n"
"    border: 1px solid #2e3440;\n"
"    border-radius: 2px;\n"
"}\n"
"  \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 101, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 120, 121, 41))
        self.label_2.setObjectName("label_2")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setEnabled(True)
        self.select.setGeometry(QtCore.QRect(440, 160, 41, 30))
        self.select.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/upload-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select.setIcon(icon)
        self.select.setObjectName("select")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(150, 200, 191, 31))
        self.run.setObjectName("run")
        self.path = QtWidgets.QLineEdit(self.centralwidget)
        self.path.setGeometry(QtCore.QRect(30, 160, 401, 30))
        self.path.setObjectName("path")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(110, 270, 261, 37))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 310, 61, 20))
        self.result.setObjectName("result")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(150, 0, 181, 31))
        self.title.setObjectName("title")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(80, 320, 341, 131))
        self.textEdit.setObjectName("textEdit")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(170, 70, 82, 17))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(170, 90, 91, 17))
        self.radioButton_2.setObjectName("radioButton_2")
        self.bodyLabel = QtWidgets.QLabel(self.centralwidget)
        self.bodyLabel.setGeometry(QtCore.QRect(80, 230, 341, 61))
        self.bodyLabel.setWordWrap(True)
        self.bodyLabel.setObjectName("bodyLabel")
        self.canoeStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.canoeStatusLabel.setGeometry(QtCore.QRect(330, 70, 141, 31))
        self.canoeStatusLabel.setText("")
        self.canoeStatusLabel.setObjectName("canoeStatusLabel")
        self.serverStatusLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverStatusLabel.setGeometry(QtCore.QRect(350, 10, 121, 31))
        self.serverStatusLabel.setText("")
        self.serverStatusLabel.setObjectName("serverStatusLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHistory = QtWidgets.QMenu(self.menubar)
        self.menuHistory.setObjectName("menuHistory")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSettings.addAction(self.actionExit)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CANoe Status"))
        self.label_2.setText(_translate("MainWindow", "Select .cmm file:"))
        self.select.setToolTip(_translate("MainWindow", "Choose a file"))
        self.run.setText(_translate("MainWindow", "Run Script"))
        self.result.setText(_translate("MainWindow", "Result :"))
        self.title.setText(_translate("MainWindow", "CMM Runner"))
        self.radioButton.setText(_translate("MainWindow", "Connected"))
        self.radioButton_2.setText(_translate("MainWindow", "not connected"))
        self.bodyLabel.setText(_translate("MainWindow", "Please wait until the testing process is complete."))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHistory.setTitle(_translate("MainWindow", "History"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
