# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'historyDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryDialog(object):
    def setupUi(self, HistoryDialog):
        HistoryDialog.setObjectName("HistoryDialog")
        HistoryDialog.resize(500, 437)
        HistoryDialog.setMinimumSize(QtCore.QSize(500, 400))
        HistoryDialog.setStyleSheet("\n"
"    /* Dialog Background */\n"
"    QDialog {\n"
"      background-color: #2e3440;\n"
"    }\n"
"\n"
"    /* Title Label */\n"
"    QLabel#titleLabel {\n"
"      font: 75 24pt \"Segoe UI\";\n"
"      color: #88c0d0;\n"
"      background-color: transparent;\n"
"    }\n"
"\n"
"    /* Body Text */\n"
"    QLabel#bodyLabel {\n"
"      font: 14pt \"Segoe UI\";\n"
"      color: #d8dee9;\n"
"      background-color: transparent;\n"
"      padding: 10px;\n"
"    }\n"
"\n"
"    /* Close Button */\n"
"    QPushButton#closeButton {\n"
"      background-color: #5e81ac;\n"
"      color: white;\n"
"      border-radius: 15px;\n"
"      padding: 10px 20px;\n"
"      border: 2px solid #4c566a;\n"
"      font: 14pt \"Segoe UI\";\n"
"    }\n"
"\n"
"    QPushButton#closeButton:hover {\n"
"      background-color: #81a1c1;\n"
"      border: 2px solid #88c0d0;\n"
"    }\n"
"\n"
"    QPushButton#closeButton:pressed {\n"
"      background-color: #4c566a;\n"
"      border: 2px solid #3b4252;\n"
"    }\n"
"   ")
        self.verticalLayout = QtWidgets.QVBoxLayout(HistoryDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(HistoryDialog)
        self.titleLabel.setMinimumSize(QtCore.QSize(0, 60))
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.bodyLabel = QtWidgets.QLabel(HistoryDialog)
        self.bodyLabel.setText("")
        self.bodyLabel.setWordWrap(True)
        self.bodyLabel.setObjectName("bodyLabel")
        self.verticalLayout.addWidget(self.bodyLabel)
        self.scrollArea = QtWidgets.QScrollArea(HistoryDialog)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widget = QtWidgets.QWidget()
        self.widget.setGeometry(QtCore.QRect(0, 0, 480, 245))
        self.widget.setObjectName("widget")
        self.scrollAreaLayout = QtWidgets.QVBoxLayout(self.widget)
        self.scrollAreaLayout.setContentsMargins(10, 10, 10, 10)
        self.scrollAreaLayout.setSpacing(10)
        self.scrollAreaLayout.setObjectName("scrollAreaLayout")
        self.buttonLayout = QtWidgets.QVBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.scrollAreaLayout.addLayout(self.buttonLayout)
        self.scrollArea.setWidget(self.widget)
        self.verticalLayout.addWidget(self.scrollArea)
        self.closeButton = QtWidgets.QPushButton(HistoryDialog)
        self.closeButton.setObjectName("closeButton")
        self.verticalLayout.addWidget(self.closeButton, 0, QtCore.Qt.AlignRight)

        self.retranslateUi(HistoryDialog)
        QtCore.QMetaObject.connectSlotsByName(HistoryDialog)

    def retranslateUi(self, HistoryDialog):
        _translate = QtCore.QCoreApplication.translate
        HistoryDialog.setWindowTitle(_translate("HistoryDialog", "History"))
        self.titleLabel.setText(_translate("HistoryDialog", "History"))
        self.closeButton.setText(_translate("HistoryDialog", "Close"))
