# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cmm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 510)
        MainWindow.setStyleSheet("QWidget {\n"
"      background-color: #2e3440;\n"
"    }\n"
"    QLabel#title {\n"
"      font: 75 24pt \"Segoe UI\";\n"
"      color: #88c0d0;\n"
"      background-color: transparent;\n"
"    }\n"
"    QLabel {\n"
"      font: 12pt \"Segoe UI\";\n"
"      color:white;\n"
"      background-color: transparent;\n"
"    }\n"
"QPushButton {\n"
"      background-color: #5e81ac;\n"
"      color: white;\n"
"      border-radius: 10px;\n"
"      padding: 9px 10px;\n"
"      border: 1px solid #4c566a;\n"
"      font: 9pt \"Segoe UI\";\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"      background-color: #81a1c1;\n"
"      border: 2px solid #88c0d0;\n"
"    }\n"
"QPushButton:pressed {\n"
"      background-color: #4c566a;\n"
"      border: 2px solid #3b4252;\n"
"    }\n"
"QProgressBar{\n"
"     background-color: #5e81ac;\n"
"      color: white;\n"
"      border-radius: 13px;\n"
"      padding: 10px 10px;\n"
"      border: 1px solid #4c566a;\n"
"      font: 8pt \"Segoe UI\";\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}\n"
"  \n"
"   QMenuBar{\n"
"     color: white;\n"
"    }\n"
"QLineEdit{\n"
"  background-color: transparent;\n"
"      color: white;\n"
"      border-radius: 10px;\n"
"      padding: 5px 9px;\n"
"      border: 1px solid #4c5660;\n"
"      font: 9pt \"Segoe UI\";\n"
"}\n"
"\n"
"\n"
"QStatusBar::item {\n"
"    border: 1px solid #2e3440;\n"
"    border-radius: 2px;\n"
"}\n"
"  \n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.run = QtWidgets.QPushButton(self.centralwidget)
        self.run.setGeometry(QtCore.QRect(350, 200, 111, 31))
        self.run.setObjectName("run")
        self.progLabel = QtWidgets.QLabel(self.centralwidget)
        self.progLabel.setGeometry(QtCore.QRect(70, 230, 341, 35))
        self.progLabel.setWordWrap(True)
        self.progLabel.setObjectName("progLabel")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(140, 0, 181, 31))
        self.title.setObjectName("title")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(120, 260, 261, 37))
        self.progressBar.setMinimumSize(QtCore.QSize(0, 30))
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 451, 58))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.canStatusLabel = QtWidgets.QLabel(self.groupBox)
        self.canStatusLabel.setObjectName("canStatusLabel")
        self.horizontalLayout_2.addWidget(self.canStatusLabel, 0, QtCore.Qt.AlignRight)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.serverStatusLabel = QtWidgets.QLabel(self.groupBox)
        self.serverStatusLabel.setObjectName("serverStatusLabel")
        self.horizontalLayout_2.addWidget(self.serverStatusLabel, 0, QtCore.Qt.AlignRight)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 120, 451, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.path = QtWidgets.QLineEdit(self.groupBox_2)
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.select = QtWidgets.QPushButton(self.groupBox_2)
        self.select.setEnabled(True)
        self.select.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/upload-file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.select.setIcon(icon)
        self.select.setObjectName("select")
        self.horizontalLayout.addWidget(self.select)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 240, 431, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.res = QtWidgets.QTextEdit(self.groupBox_3)
        self.res.setObjectName("res")
        self.verticalLayout.addWidget(self.res)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 21))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHistory = QtWidgets.QMenu(self.menubar)
        self.menuHistory.setObjectName("menuHistory")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuSettings.addAction(self.actionExit)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHistory.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.run.setText(_translate("MainWindow", "Run Script"))
        self.progLabel.setText(_translate("MainWindow", "Please wait until the testing process is complete."))
        self.title.setText(_translate("MainWindow", "CMM Runner"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection Status"))
        self.canStatusLabel.setText(_translate("MainWindow", "🔴"))
        self.label.setText(_translate("MainWindow", "CANoe"))
        self.serverStatusLabel.setText(_translate("MainWindow", "🔴"))
        self.label_4.setText(_translate("MainWindow", "SERVER"))
        self.groupBox_2.setTitle(_translate("MainWindow", "script"))
        self.label_2.setText(_translate("MainWindow", ".cmm file:"))
        self.select.setToolTip(_translate("MainWindow", "Choose a file"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Result"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHistory.setTitle(_translate("MainWindow", "History"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
